services:
  - type: web
    name: yeribank-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: "10000"
      - key: APP_KAFKA_ENABLED
        value: "false"
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SECURITY_JWT_SECRET
        generateValue: true
